[[main]]
    name = "Sobre mí"
    pageRef = "about"
    weight = 10
    identifier = "about_me"

[[main]]
    name = "Proyectos"
    pageRef = "projects"
    weight = 11
    identifier = "projects"

[[main]]
    pre = "github"
    url = "https://github.com/masamionakada"
    identifier = "github"
    weight = 20

[[main]]
    pre = "linkedin"
    url = "http://linkedin.com/in/masamionakada/"
    identifier = "linkedin"
    weight = 30

[[main]]
    name = "Sobre mi"
    pageRef = "about"
    weight = 40    

[[footer]]
    pre = "github"
    url = "https://github.com/masamionakada"
    identifier = "github"
    weight = 10

[[footer]]
    pre = "linkedin"
    url = "http://linkedin.com/in/masamionakada/"
    identifier = "linkedin"
    weight = 20

[[footer]]
    pre = "instagram"
    url = "https://www.instagram.com/masamionakada/"
    identifier = "instagram"
    weight = 30